Restore services of service set on restoring service set.
Icinga/icingaweb2-module-director pull request #2420
Opened 2021-10-28 16:17 UTC by raviks789

All the services which were under the service set when it was deleted must be restored when it is restored from activity log.

dependent on PR: #2418 

fix #1065

2021-12-13 11:53 UTC, lippserd commented
ref/IP/35863

2022-02-28 12:23 UTC, Thomas-Gelf commented
Hi @raviks789,

thank you for this PR! Main problems:

* it doesn't work with PostgreSQL (can be fixed)
* it's a wild hack (per design, that's not your fault - it's a tricky task)

You correctly figured out, that  related Service activities must have their Activity (Removal) Log somehow being triggered. I'd have had preferred a direct call to `DirectorActivityLog::logRemoval()` for each service - depending on a specific `onDelete`-Implementation is fragile.

But please let me propose a different implementation. The main issue here is how deletion takes place. A user issues a single operation ("Delete a Service Set"), but behind the scenes, multiple operations take place. For a better end user experience, this should be "one step" throughout the UI. Read: there should be only one entry in the Activity Log.

This sounds tricky, but the good news is: most of the related work has already been done. `IcingaServiceSet` implements the `ExportInterface`, and therefore has import/export-Methods. They're being used by our Configuration Baskets, and have one big advantage: no fiddling with IDs on restore. It is up to you to figure out, how this then fits into our current Show-Config-Diff-Implementation ;-)

Could you please give that approach a try? Only if you find the time of course, otherwise please let me know. I'm allowed to dedicate some time to similar tasks this week.

Thanks a lot,
Thomas

2022-02-28 12:26 UTC, Thomas-Gelf submitted a review, later dismissed
.

2022-03-31 07:34 UTC, tbauriedel commented
ref/NC/732413

2024-02-05 15:03 UTC, nilmerg reviewed
The export/import logic wasn't removed, only moved. (56f81b91bb0cd4f8be6e9d2aa11509659c5620a5) Isn't it still applicable here?

2024-02-07 11:04 UTC, nilmerg requested changes

2024-02-07 11:04 UTC, nilmerg commented on library/Director/Web/Widget/ActivityLogInfo.php
> +                $serviceProps['imports'] = $service->imports;
Please make sure all configurable properties are restored.

2024-02-07 12:38 UTC, nilmerg approved these changes

2024-02-07 12:40 UTC, merged