add support for icingadb as only icingaweb2 data backend
Icinga/icingaweb2-module-director pull request #2635
Opened 2022-10-12 15:18 UTC by EmTeedee

Hi,

we're using icingadb exclusively and I wanted director to be integrated properly.
I've tested this PR with only icingadb, only monitoring and both enabled.

fixes #2533 

Tobias

2022-10-19 15:24 UTC, EmTeedee commented
@Thomas-Gelf could you comment on this PR and let me know if I need to make any changes?
I'm not super happy with the MonitorBackend interface, but not sure how to handle that better.

2022-11-22 05:41 UTC, mwaldmueller commented
@Thomas-Gelf Any news on this? Problem still exists with Icinga DB Web v1.0.2

2023-09-21 08:48 UTC, Yoda-BZH commented
Hello,

Any update ? Thank you !

2023-11-13 12:39 UTC, sukhwinder33445 commented
Hi @EmTeedee,

Sorry for the late reply. I'd love to give you some code reviews/comments, so we can merge this branch as soon as possible. However, many changes have been made to the base branch since the last commit, so this branch must first be rebased with main in order to resolve the conflicts. 
Are you still interested in fixing these conflicts and making some more code changes when I review the code? Otherwise, I can make the further changes myself.

2023-11-15 16:22 UTC, EmTeedee commented
@sukhwinder33445 I currently can't spare the time. We're very busy at work...

2023-11-16 07:20 UTC, sukhwinder33445 commented
Thank you for your reply @EmTeedee. Then I will take over from now on.

2023-11-22 09:35 UTC, sukhwinder33445 commented on application/controllers/HostController.php
> +            && $backend->canModifyService($hostName, $serviceName)
The permission check can be added directly to `canModifyService()` method.

2024-01-15 14:43 UTC, nilmerg requested changes

2024-01-16 08:53 UTC, nilmerg requested changes

2024-01-16 08:53 UTC, nilmerg commented on library/Director/Integration/Icingadb/IcingadbBackend.php
> +    protected $isAvailable;
That's only used internally and without Icinga DB Web being enabled, this class isn't instantiated to begin with. So please remove this property.

2024-01-16 08:53 UTC, nilmerg commented on library/Director/Integration/BackendInterface.php
> +    public function isAvailable(): bool;
Since this will be exclusive to the monitoring backend, I'd suggest to remove this from the interface.

2024-01-16 10:16 UTC, merged