Avoid usage of dynamic properties
Icinga/icingaweb2-module-director pull request #2792
Opened 2023-08-29 10:50 UTC by raviks789

Dynamic properties are deprecated in PHP 8.2 and must be avoided.

2023-08-31 08:37 UTC, nilmerg requested changes
please add phpstan with level 2 to the workflow configuration. Plus a baseline configuration.

2023-08-31 08:38 UTC, nilmerg commented
Workflow configuration is available in master since today. And of course, add PHP 8.2 to the matrix.

2023-09-01 06:51 UTC, nilmerg commented on .github/workflows/php.yml
> +          git clone --depth 1 -b main https://github.com/Icinga/icingaweb2-module-cube.git vendor/cube
please remove -b main, shouldn't be necessary

2023-09-01 06:54 UTC, nilmerg commented
Please also take a look at the unit test output on PHP 8.1 and 8.2. There are still some deprecations logged.

2023-09-01 10:58 UTC, raviks789 commented
> Please also take a look at the unit test output on PHP 8.1 and 8.2. There are still some deprecations logged.

This is because the replaced `ramsey/collection` package loses the PHP 8.1 support patch written in icinga-php-thirdparty. There is an issue gipfl/icinga-bundles#1 opened in gipfl/icinga-bundles repository for this.

2023-09-01 14:03 UTC, nilmerg approved these changes

2023-09-04 07:43 UTC, Thomas-Gelf requested changes
@raviks789: good work, thank you! Could you please install the incubator version required in our module.info? If parsing the file annoys you, I'm fine with a hard-coded one for our tests, which can be raised once required.

Testing with unreleased dependencies is a good thing, which could be added as an optional/additional workflow. Main priority should be testing what's going to be installed. This then also removes the requirement to track incubator module dependencies in a second place.

Many thanks
Thomas

2023-09-04 10:32 UTC, nilmerg commented
The installed incubator version has been introduced by #2309, not here. And this has the same intended effect as the just mentioned change: Testing the *current* state. If you want a stable test workflow, we should add this separately. Though, only for `release/*` branches or similar, there's no reason to run such a test on every push.

2023-09-04 11:44 UTC, Thomas-Gelf commented
For the Director testing with library versions it will never run with has absolutely no purpose. Here we're testing the current Director state, and not any intermediary foreign library state, that might or might not be released.

2023-09-21 07:00 UTC, merged

2023-09-21 07:01 UTC, Thomas-Gelf commented
Merged, thank you!