Fix form field suggestions
Icinga/icingaweb2-module-director pull request #2840
Opened 2023-12-05 10:30 UTC by raviks789

Other available fields should be suggested when no check command has been chosen for service template.

fixes #2826, #2815

2023-12-05 10:42 UTC, RincewindsHat commented
does not work for notifications for a first test

2023-12-06 09:32 UTC, raviks789 commented
> does not work for notifications on a first test

As discussed offline, this is a fix for the bug where the data fields are not available for selection when the check commands are not selected (Not a feature to show the custom properties of notification command the notifications form).

2024-01-05 07:40 UTC, bigfreak85 commented
works and has helped me to get the job done

2024-01-09 14:08 UTC, nilmerg requested changes

2024-01-09 14:08 UTC, nilmerg commented on application/forms/IcingaObjectFieldForm.php
> -    protected static function getFilterFields(IcingaObject $object): array
Why did you remove this? It doesn't seem relevant to the fix.

2024-01-12 14:21 UTC, nilmerg requested changes

2024-01-12 14:21 UTC, nilmerg commented on test/php/library/Director/Form/IcingaObjectFieldFormTest.php
> +        $this->app()->setRequest(new Request());
This is not required if the director's `BaseTestCase` extends Icinga Web's `BaseTestCase`. At least, works for me locally. Remember to call the parent's `setUp` then.

2024-01-12 14:21 UTC, nilmerg commented on test/php/library/Director/Form/IcingaObjectFieldFormTest.php
> +            $this->tearDown();
Don't call this in `setUp`. I don't even dare to think of the side effects.

2024-01-12 14:21 UTC, nilmerg commented on test/php/library/Director/Form/IcingaObjectFieldFormTest.php
> +    public function tearDown(): void
Call the parent once `BaseTestCase` extends `Icinga\Test\BaseTestCase`

2024-01-16 12:02 UTC, nilmerg requested changes

2024-01-16 15:56 UTC, nilmerg approved these changes

2024-01-16 15:56 UTC, merged