Support Content-Security-Policy
Icinga/icingaweb2-module-director pull request #2857
Opened 2024-01-12 15:01 UTC by sukhwinder33445

2024-01-17 16:04 UTC, raviks789 commented on public/css/module.less
> +//DataController::dictionaryAction, cannot findusage in web
You can remove this comment, I have tested this.

2024-01-18 09:08 UTC, raviks789 commented on application/forms/AddToBasketForm.php
> +            (array) implode(", ", $names)
instead of casting the string to array could you not perform string concatenation?

2024-01-18 15:37 UTC, nilmerg requested changes
There's still an onclick attribute defined in `ImportsourceController:183`

2024-01-19 14:12 UTC, nilmerg approved these changes

2024-01-19 14:12 UTC, nilmerg commented
please rebase

2024-01-25 09:44 UTC, merged