added conversion from array to object for the directory to row property modifier
Icinga/icingaweb2-module-director pull request #2923
Opened 2024-09-30 14:05 UTC by MisterMountain

Without this fix modifying an import source fails, if you try to clone the row for every entry of your nested dictionary/hash structure due to a missing array to object conversion

2024-10-28 08:25 UTC, lippserd approved these changes

2024-11-07 08:41 UTC, lippserd requested changes
@MisterMountain Please fix the [code sniffer complaints](https://github.com/Icinga/icingaweb2-module-director/actions/runs/11719251205/job/32642415893?pr=2923#step:7:12).

2026-01-14 11:30 UTC, raviks789 commented
@MisterMountain Could you add an example for this scenario in the description?

Also, please rebase with the master branch. And by looking at the indentation of the `if` block I don't think all the codesinffer complaints were fixed. Have a look at it once the branch is rebased.

2026-09-15 13:06 UTC, raviks789 commented
@MisterMountain, reproduced this issue. See the steps below:

Steps to reproduce the original issue

  - Create an Import Source in Director (Source Type: SQL, any DB resource works).
  - Use this query, which returns one row with a text column holding some JSON:
  SELECT 'host1' AS `key`, '{"nginx": {"port": 80}, "logging": []}' AS services
  - On that Import Source, open the Modifiers tab and add two modifiers on the services column, in this order:
    a. "Decode a JSON string"
    b. "Clone the row for every entry of a nested Dictionary/Hash structure" (Key Property Name: service_name)
  - Open the Preview tab.
  - Result: the preview fails with Nested "logging" dictionary expected, got array (PropertyModifierDictionaryToRow.php:82), even though logging simply has no extra properties. The whole
    import source stops working, not just that one entry.

2026-09-15 13:10 UTC, raviks789 requested changes

2026-09-15 13:10 UTC, raviks789 commented on library/Director/PropertyModifier/PropertyModifierDictionaryToRow.php
>              if (! is_object($properties)) {
The issue occurs due to empty array as empty array and empty object carry nothing in it they both can be treated the same, but the array with actual items in it should still fail.

```suggestion
            if (is_array($properties) && empty($properties)) {
            $properties = (object) $properties;
            }
            
if (! is_object($properties)) {
```

2026-09-16 08:03 UTC, merged