#2885 Fix MySQL8.4 nonstandard foreign keys deprecation
Icinga/icingaweb2-module-director pull request #2946
Opened 2024-12-19 16:18 UTC by mcsken

- See https://github.com/Icinga/icingaweb2-module-director/issues/2885 (and my comment on the issue).
 - Fix MySQL-8.4 nonstandard foreign keys deprecation.
 
> [!IMPORTANT]  
> I have no previous MySQL experience. This is working queries I generated with the help of AI, and tested locally that it works for my setup using the latest latest MySQL (version 8.4.3) while setting up the Director module on Icinga Web 2 for the first time. Someone with more experience in MySQL should review it, and ideally merge a fix ASAP because it leads to a broken setup for new users (and whoever upgrades MySQL to 8.4+) with a essentially useless SQL error message for a user, which I found no reference to when searching the documentation or online.

The main error the user would normally see looks something like:
```
Migration 0 failed (SQLSTATE[HY000]: General error: 6125 Failed to add the foreign key constraint. Missing unique key for constraint 'director_generated_config_activity' 'director_generated_config_activity' in the referenced table 'director_activity_log'...
```
![director-error-messages](https://github.com/user-attachments/assets/e79f9544-ff6b-42a3-8b1e-3d49eacc2f7e)

2024-12-19 16:27 UTC, mcsken commented
Not happy I had to sign something for an open source PR, but I signed it....

2024-12-19 20:06 UTC, roskakori commented on schema/mysql.sql
> +  UNIQUE INDEX idx_checksum (checksum)
```suggestion
  UNIQUE INDEX idx_checksum (checksum)
```
Setting the index once should suffice.

2024-12-20 07:32 UTC, bobapple commented
@cla-bot check

2024-12-20 13:06 UTC, mcsken commented
I looked into this a bit more and tried to clean up the AI code:
 - Removed what I believe are duplicate/unnecessary indexes from the original commit.
 - Sticked to the projects original naming and formatting conventions.

Someone ofc should still review it properly, and potentially even test it because I only tested the original commit on my machine.

2025-03-25 08:47 UTC, lippserd requested changes
@raviks789 Can you make the change and squash the commits so we can merge this as soon as possible?

2025-03-25 08:47 UTC, lippserd commented on schema/mysql-migrations/upgrade_188.sql
> +ALTER TABLE director_generated_config
The constraint should be removed beforehand. Otherwise this will lead to duplicate key errors.

2025-03-25 10:26 UTC, raviks789 commented on schema/mysql-migrations/upgrade_188.sql
> +ALTER TABLE director_generated_config
Done

2025-03-25 11:13 UTC, roskakori commented
Maybe I am missing something, but what is the purpose of a foreign key using the `checksum` instead of the `id`? I'd imagine that the `checksum` is not guaranteed to be unique.

2025-03-25 12:42 UTC, lippserd approved these changes

2025-03-25 14:08 UTC, raviks789 commented
@roskakori I cannot answer why the foreign key is a checksum, but after this change here the checksum would have to be unique. So the uniqueness is going to be guaranteed.

2025-03-25 14:42 UTC, merged